export const SET_TOKEN = 'SET_TOKEN'

export const IS_FETCHING_LOGGING_IN = 'IS_FETCHING_LOGGING_IN'
export const SET_LOGGED_USER = 'SET_LOGGED_USER'

export const IS_FETCHING_REGISTER = 'IS_FETCHING_REGISTER'
export const SET_REGISTERED_USER = 'SET_REGISTERED_USER'
